export const ENDPOINTS = {
  auth: {
    login: "/auth/login/",
    me: "/accounts/me/",
  },
  users: "/accounts/users/",
  emailRecipients: "/accounts/email-recipients/",
  sendEmail: "/accounts/send-email/",
  semesters: "/academics/semesters/",
  courses: "/academics/courses/",
  enrollments: "/academics/enrollments/",
  groups: "/groups/groups/",
  groupMembers: "/groups/members/",
  notifications: "/common/notifications/",
  conversations: "/common/conversations/",
  conversationRecipients: "/common/conversations/recipients/",
  conversationUnread: "/common/conversations/unread-count/",
  whatsappSettings: "/common/whatsapp/settings/",
  sendWhatsapp: "/common/whatsapp/send/",
  courseworks: "/coursework/courseworks/",
  submissions: "/coursework/submissions/",
  feedback: "/coursework/feedback/",
};
