# Generated by Django 5.1.15 on 2026-04-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursework',
            name='lock_at_due_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coursework',
            name='submission_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('both', 'Both')], max_length=20),
        ),
    ]
