# Generated by Django 5.1.15 on 2026-04-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0002_coursework_lock_at_due_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursework",
            name="max_group_members",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
