# Generated by Django 5.1.15 on 2026-04-13 14:05

import django.core.validators
from django.db import migrations, models

import apps.coursework.models


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0003_coursework_max_group_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="approval_status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="topic",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="submission",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.coursework.models.submission_upload_path,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "docx", "zip", "pptx"])],
            ),
        ),
    ]
