# Generated by Django 5.1.15 on 2026-04-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0004_submission_topic_approval_status_and_file_optional"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="requested_member_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
