# Generated by Django 5.1.15 on 2026-04-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroup',
            name='coursework_type',
            field=models.CharField(choices=[('assignment', 'Assignment'), ('quiz', 'Quiz'), ('exam', 'Exam'), ('presentation', 'Presentation'), ('project', 'Project')], default='project', max_length=20),
        ),
    ]
