# Generated by Django 5.1.15 on 2026-04-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_studentgroup_coursework_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='invitation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='accepted', max_length=20),
        ),
    ]
