# Generated by Django 5.1.15 on 2026-04-13 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_groupmember_invitation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
