# Generated by Django 5.1.15 on 2026-04-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coursework", "0002_coursework_lock_at_due_time_and_more"),
        ("groups", "0004_studentgroup_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="coursework",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="student_groups",
                to="coursework.coursework",
            ),
        ),
        migrations.AddField(
            model_name="studentgroup",
            name="scope",
            field=models.CharField(
                choices=[
                    ("global", "Overall (All Courses)"),
                    ("course", "Per Course"),
                    ("coursework", "Per Coursework"),
                ],
                default="course",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="studentgroup",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.deletion.CASCADE,
                related_name="student_groups",
                to="academics.course",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentgroup",
            unique_together=set(),
        ),
    ]
