# Generated by Django 5.1.15 on 2026-04-13 16:20

from django.db import migrations, models


def backfill_group_source(apps, schema_editor):
    StudentGroup = apps.get_model("groups", "StudentGroup")
    StudentGroup.objects.filter(coursework__isnull=False).update(source="coursework_submission")
    StudentGroup.objects.filter(scope="coursework").update(source="coursework_submission")


def reverse_backfill_group_source(apps, schema_editor):
    StudentGroup = apps.get_model("groups", "StudentGroup")
    StudentGroup.objects.filter(source="coursework_submission").update(source="manual")


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0005_studentgroup_scope_and_coursework"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentgroup",
            name="source",
            field=models.CharField(
                choices=[("manual", "Manual"), ("coursework_submission", "Coursework Submission")],
                default="manual",
                max_length=30,
            ),
        ),
        migrations.RunPython(backfill_group_source, reverse_backfill_group_source),
    ]
